# Generated by Django 6.0.5 on 2026-05-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='structure.department', verbose_name='Подразделение'),
        ),
    ]
