# Generated by Django 6.0.5 on 2026-05-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_employee_departament_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departament_id',
            new_name='department_id',
        ),
    ]
