# Generated by Django 6.0.5 on 2026-05-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_rename_departament_id_employee_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='structure.department', verbose_name='Связанное подразделение'),
        ),
    ]
